git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: O
    context: files
    command: env OCO_GITPUSH=false oco --yes
    subprocess: true
  - key: '<c-p>'
    context: 'files'
    command: 'git ls-files | fzf --preview="bat --color always {}" | xargs -r nvim'
    subprocess: true
